name: Publish NuGet and upload release

on:
  release:
    types: [ "published" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0

      - name: Download NuGet
        id: download-nuget
        run: |
          sudo curl -o /usr/local/bin/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

      - name: Build the solution
        run: dotnet build "Premonition.sln" -c Release

      - name: Extract current version
        id: get-version
        run: |
          version=$(jq -r '.version' plugin_template/swinfo.json)
          echo "Version is $version"
          echo "version=$version" >> $GITHUB_ENV
          echo "artifact_name_bie=Premonition-BepInEx-$version.zip" >> $GITHUB_ENV
          echo "zip_bie=$(ls -1 dist/Premonition-BepInEx-*.zip | head -n 1)" >> $GITHUB_ENV
          echo "artifact_name_sw=Premonition-SpaceWarp-$version.zip" >> $GITHUB_ENV
          echo "zip_sw=$(ls -1 dist/Premonition-SpaceWarp-*.zip | head -n 1)" >> $GITHUB_ENV
          echo "upload_url=$(wget -qO- https://api.github.com/repos/$GITHUB_REPOSITORY/releases | jq '.[0].upload_url' | tr -d \")" >> $GITHUB_ENV
          wget -qO- https://api.github.com/repos/$GITHUB_REPOSITORY/releases | jq -r '.[0].body' > ./changelog.md

      - name: Publish NuGet package
        run: |
          nupkg_path=$(ls -1 nuget/Premonition.Core.*.nupkg | head -n 1)
          dotnet nuget push "$nupkg_path" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
          
      - name: Upload BepInEx Zip
        uses: shogo82148/actions-upload-release-asset@v1.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: ${{ env.zip_bie }}
          asset_name: ${{ env.artifact_name_bie }}
          asset_content_type: application/zip
          
      - name: Upload SpaceWarp Zip
        uses: shogo82148/actions-upload-release-asset@v1.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: ${{ env.zip_sw }}
          asset_name: ${{ env.artifact_name_sw }}
          asset_content_type: application/zip
     # TODO: SpaceDock stuff
